const CONFIG = {
    introTitle: 'aloo ebe của a :>>',
    introDesc: `hihi hôm nay a có quà cho bé nha',
    btnIntro: 'hihi',
    title: 'đây là món quà mà a dành cho bé nhân kỉ niệm một tháng của tụi mình  ',
    desc: 'bé có thích khum',
    btnYes: 'cóa :)))',
    btnNo: 'Không, có cái qq :3',
    question:'thấy a đỉnh không :>>>',
    btnReply: 'Gửi cho a <3',
    reply: 'đỉnh lắm luôn <33333333',
    mess: 'a biết mà khen hoài :)))',
    messDesc: 'a hi vọng hai đứa mình sớm có dịp gặp nhau để a còn đc ôm bé nựa.',
    btnAccept: 'Okiiiii lun <3',
    
