const CONFIG = {
    introTitle: 'hello ebe của a nha !',
    introDesc: `thì hôm nay là kỉ niệm 1 tháng của cả hai đứa `,
    btnIntro: 'hihi',
    title: 'Anh muốn nói là a iu bé lắm 😙',
    desc: 'Có thể là sau này có những lúc cãi vã bé nhớ bỏ qua cho a nhaaa',
    btnYes: 'ukiiiii <33',
    btnNo: 'Không,mơ à :((',
    question:'hihi bé vẫn còn iu a lắm đkhummm',
    btnReply: 'Gửi cho anh <3',
    reply: 'anh là số 1 hihi cho phép a có thêm vài bạn gái nữa :>>',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'hihi ráng chờ a nhaaa.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com'//https://www.facebook.com/profile.php?id=100033987262040
